services: "2.4"
  centra_nginx:
    container_name: centra_nginx
    depends_on:
      - centra_php
    ports:
      - 88:80
    networks:
      centra-docker:
        aliases:
          - centra.docker.localhost
    image: nginx:stable
    volumes:
      - ./html:/var/www/html:cached
      - ./docker/nginx/centra.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d

  centra_php:
    build:
      context: ./docker/php
    container_name: centra_php
    env_file:
      - ./html/.env
      - ./docker/php/.env.dev
    networks:
      - centra-docker
    volumes:
      - ./html:/var/www/html

  centra_redis:
    container_name: centra_redis
    image: redis:latest
    networks:
      - centra-docker

networks:
  centra-docker:
